### ISSUE TITLE
Retrieve DB name from influxdb

### ISSUE THREAD

**Issue by florasamuel** [wise-coders/dbschema#112]
Hi,

I am using dbschema 9.4.1 and trying to connect to influxdb using dbschema, however it returns 400 error.

com.influxdb.exceptions.BadRequestException: HTTP status code: 400; Message: failed to decode request body: organization name "SAP?days=" not found
  at com.influxdb.internal.AbstractRestClient.responseToError(AbstractRestClient.java:113)
  at com.influxdb.internal.AbstractQueryApi$1.onResponse(AbstractQueryApi.java:220)
  at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:247)
  at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:199)
  at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:131)
  at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:939)
  at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:123)
  at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:85)
  at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:75)
  at com.wisecoders.dbschema.influxdb.InfluxMetaData.getSchemas(InfluxMetaData.java:31)
  at com.wisecoders.dbs.dbms.Dbms.listSchemasAndCatalogs(Dbms.java:287)
  at com.wisecoders.dbs.dbms.Dbms.loadSchemasAndCatalogs(Dbms.java:265)
  at com.wisecoders.dbs.dbms.reverseEngineer.tasks.FxImportSelectionTask.a(FxImportSelectionTask.java:41)
  at com.wisecoders.dbs.dbms.reverseEngineer.tasks.FxImportSelectionTask.call(FxImportSelectionTask.java:20)

Provided we have buckets in influxdb, what valu should be entered in organization field?

**Comment by florasamuel** [comment]
Found the issue. replaced ? in JDBC url with & using Edit manually option and it worked.

JDBC url: http://<HOST>:<PORT>?org=<DB>**&**days=<PARAM>

**Comment by wise-coders** [comment]
Thank you for writing about the fix. May I ask, were did you saw the URL with two '?'?
I mean the wrong one: https://host:PORT/DB?org=PARAM?token=PARAM2
Was this in DbSchema, in help or other place? We would fix this. I am not sure where to check.

**Comment by florasamuel** [comment]
<img width="526" alt="image" src="https://github.com/wise-coders/dbschema/assets/34363034/38f8dc32-0b5a-4a1e-9740-a48aac0f4e26">

**Comment by florasamuel** [comment]
same when i choose the HTTPs option for JDBC URL.

**Comment by wise-coders** [comment]
Could you please install the latest DbSchema version 9.4.1. from the website ? It should have this issue fixed. If not, please write back and we will check again with high priority.

**Comment by wise-coders** [comment]
Best regards,
 Dragos Pruteanu

> On Friday, August 11, 2023 at 1:18:33 PM, DaveDevelop wrote:
>
> same when i choose the HTTPs option for JDBC URL.
> —
> Reply to this email directly, [1] view it on GitHub, or [2] unsubscribe.
> You are receiving this because you commented.Message ID:

[1] https://github.com/wise-coders/dbschema/issues/112#issuecomment-1674586699

**Comment by florasamuel** [comment]
Sure...Thanks a lot for the fix...will try with the newer version and update soon

**Comment by wise-coders** [comment]
I consider the issue closed. Please reopen the ticket if is the case.
