### ISSUE TITLE
Java error when adding new table to layout

### ISSUE THREAD

**Issue by kamiller42** [wise-coders/dbschema#19]
DbSchema 8.2.8 build 200302 on Windows 10.

Model has 3 schemas and 20 or less tables.
1. Added a new layout.
2. Executed Control-T to create new table, selected schema, and  then exception raised.

Exception stack:
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.runtime.InvokerHelper
  at groovy.lang.GroovyObjectSupport.getDefaultMetaClass(GroovyObjectSupport.java:59)
  at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:32)
  at groovy.lang.Binding.<init>(Binding.java:35)
  at com.wisecoders.dbs.forms.model.data.GroovyBindingWithDefaultForAllVariables.<init>(GroovyBindingWithDefaultForAllVariables.java:12)
  at com.wisecoders.dbs.rdbms.sync.engine.diffs.SimpleStatement.<init>(SimpleStatement.java:22)
  at com.wisecoders.dbs.schema.NameFinder.b(NameFinder.java:104)
  at com.wisecoders.dbs.dialogs.layout.FxTableEditor.<init>(FxTableEditor.java:81)
  at com.wisecoders.dbs.project.fx.frame.FxFrame.newTable(FxFrame.java:1088)
  at com.wisecoders.dbs.sys.Rx.a(Rx.java:151)
  ...

From Output log:
11:12:27  > newTable
11:12:27 Dialog New Table
11:12:29 Error handling method 'newTable' in class com.wisecoders.dbs.project.fx.frame.FxFrame: 
java.lang.ExceptionInInitializerError
  at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:86)
  at groovy.lang.GroovyObjectSupport.getDefaultMetaClass(GroovyObjectSupport.java:59)
  at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:32)
  at groovy.lang.Binding.<init>(Binding.java:35)
  at com.wisecoders.dbs.forms.model.data.GroovyBindingWithDefaultForAllVariables.<init>(GroovyBindingWithDefaultForAllVariables.java:12)
  at com.wisecoders.dbs.rdbms.sync.engine.diffs.SimpleStatement.<init>(SimpleStatement.java:22)
  at com.wisecoders.dbs.schema.NameFinder.b(NameFinder.java:104)
  at com.wisecoders.dbs.dialogs.layout.FxTableEditor.<init>(FxTableEditor.java:81)
  at com.wisecoders.dbs.project.fx.frame.FxFrame.newTable(FxFrame.java:1088)
  at com.wisecoders.dbs.sys.Rx.a(Rx.java:151)
  ...11:12:29 java.lang.ExceptionInInitializerError
	at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:86)
	at groovy.lang.GroovyObjectSupport.getDefaultMetaClass(GroovyObjectSupport.java:59)
	at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:32)
	at groovy.lang.Binding.<init>(Binding.java:35)
	at com.wisecoders.dbs.forms.model.data.GroovyBindingWithDefaultForAllVariables.<init>(GroovyBindingWithDefaultForAllVariables.java:12)
	at com.wisecoders.dbs.rdbms.sync.engine.diffs.SimpleStatement.<init>(SimpleStatement.java:22)
	at com.wisecoders.dbs.schema.NameFinder.b(NameFinder.java:104)

**Comment by wise-coders** [comment]
Please download and install the DbSchema 8.2.8 from today from website.
The error you got is related to Java, it seems the Groovy library is not loaded correctly.
If the issue persist please let me know which Java is in use ( look in Help / About dialog ).

**Comment by wise-coders** [comment]
Please install the current DbSchema version 8.2.8 from website. We think this issue is related to Java.
If the issue still persist please let me know which information is displayed in Help /About dialog.
Eventually, if is fine for you, could we arrange a web meeting ( Skype, Gooogle hangouts or Zoom - we are user DbSchema on them ) ?

Best regards,
 Dragos Pruteanu

--
 DbSchema - Wise Coders GbmH
82256 Fürstenfeldbruck bei München
 Email: support@dbschema.com - Web: [1] http://dbschema.com/

--

[1] http://www.example.com/

**Comment by kamiller42** [comment]
I was running prior version from an extracted zip file. It prompted me to install latest, DbSchema 8.2.8 build 200302 . I did by overwriting folder contents. Exception occurred and I reported.

Just ran the installer version. It is working now. Thanks.
