### ISSUE TITLE
Issue when adding a new collection to a project (just started after upgrade to latest version)

### ISSUE THREAD

**Issue by davemalinson** [wise-coders/dbschema#21]
1. Please check DbSchema Help / Output logs for errors.

java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.runtime.InvokerHelper
  at groovy.lang.GroovyObjectSupport.getDefaultMetaClass(GroovyObjectSupport.java:59)
  at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:32)
  at groovy.lang.Binding.<init>(Binding.java:33)
  at com.wisecoders.dbs.forms.model.data.GroovyBindingWithDefaultForAllVariables.<init>(GroovyBindingWithDefaultForAllVariables.java:12)
  at com.wisecoders.dbs.rdbms.sync.engine.diffs.SimpleStatement.<init>(SimpleStatement.java:22)
  at com.wisecoders.dbs.schema.NameFinder.b(NameFinder.java:105)
  at com.wisecoders.dbs.dialogs.layout.FxTableEditor.<init>(FxTableEditor.java:67)
  at com.wisecoders.dbs.project.fx.frame.FxFrame.newTable(FxFrame.java:1088)
  at com.wisecoders.dbs.sys.Rx.a(Rx.java:151)
  ...

2. Please include the DbSchema version, operating system and used database

8.2.8 build 200313, Windows 10, MongoDB

3. The steps to reproduce this issue

Just clicking on Create collection (any of the methods ie. right click, from top menu) will produce a popup Error Dialog box with the above error.

**Comment by wise-coders** [comment]
Hello,
This issue is related to Java. For some reason the Groovy libraries are not loaded correctly. Could you please check which Java is used in the Help / About dialog ? Have you used the zip installer or the exe or dmg one ? The exe and dmg comes with embedded Java, which should work better.
