### ISSUE TITLE
Ctrl + Z does not work in Apple Mac , the previous actions is not re-done

### ISSUE THREAD

**Issue by maarguedas** [wise-coders/dbschema#23]
1. Please check DbSchema Help / Output logs for errors.

2. Please include the DbSchema version, operating system and used database

3. The steps to reproduce this issue

Java Output:
java.lang.StringIndexOutOfBoundsException: index 0,length 0
  at java.base/java.lang.String.checkIndex(String.java:3679)
  at java.base/java.lang.AbstractStringBuilder.deleteCharAt(AbstractStringBuilder.java:976)
  at java.base/java.lang.StringBuilder.deleteCharAt(StringBuilder.java:291)
  at com.wisecoders.dbs.sql.editor.TextLine.a(TextLine.java:29)
  at com.wisecoders.dbs.sql.editor.undo.InsertCharChange.b(InsertCharChange.java:29)
  at com.wisecoders.dbs.sql.editor.FxCodeModel.r(FxCodeModel.java:427)
  at com.wisecoders.dbs.sql.editor.FxCodePaneBase.x(FxCodePaneBase.java:723)
  at com.wisecoders.dbs.sql.fx.FxSqlEditor.undo(FxSqlEditor.java:542)
  at com.wisecoders.dbs.sys.Rx.a(Rx.java:151)
  at com.wisecoders.dbs.sys.fx.FxUtil.a(FxUtil.java:184)
  at com.wisecoders.dbs.project.fx.frame.FxFrame.a(FxFrame.java:218)
  ...

**Comment by dprutean** [comment]
Thank you for reporting this bug. The fix will be released in the next minor update.
