### ISSUE TITLE
Can't insert record in table, mysql

### ISSUE THREAD

**Issue by danito8905** [wise-coders/dbschema#26]
**DbSchema version: 8.2.9 build 200327
Operating system: Kubuntu 19.10
Database: MySQL Server 8.0.19** 

If I try to insert a record using the Data Browser I get the following error. The SQL History show the malformed query.

![image](https://user-images.githubusercontent.com/29113406/79921722-3c550b80-8409-11ea-81a6-08a36b92e834.png)

`java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''COLOR' ) VALUES (  )' at line 1
  at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
  at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
  at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
  at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
  at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
  at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
  at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
  at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
  at com.wisecoders.dbs.rdbms.connect.model.envoy.DirectUpdate.a(DirectUpdate.java:27)
  at com.wisecoders.dbs.rdbms.connect.model.envoy.Envoy.a(Envoy.java:102)
  at com.wisecoders.dbs.browse.query.BrowseSqlStore.b(BrowseSqlStore.java:156)
  at com.wisecoders.dbs.browse.fx.FxBrowseFrame$CommitRecordTask.a(FxBrowseFrame.java:505)
  at com.wisecoders.dbs.browse.fx.FxBrowseFrame$CommitRecordTask.call(FxBrowseFrame.java:488)`

**Comment by wise-coders** [comment]
Please download and install the current DbSchema from website. Is still version 8.2.9 but a higher build number. We had a bug fix reagarding insert in Relational Data Browse. I have tested now and for me it works fine. Please let me know if the issue still persist, and if this is the case please send me the CREATE TABLE statement so I can test the same context.

**Comment by danito8905** [comment]
Perfect. Its works!! Thanks ;)
