### ISSUE TITLE
Groovy: Importing External Classes

### ISSUE THREAD

**Issue by sterlingalston** [wise-coders/dbschema#43]
Having trouble trying to run this code.  Where/ how can I import driver to get it working?

1. Please check DbSchema Help / Output logs for errors.

10:29:24 java.lang.Exception: java.lang.ClassNotFoundException: com.amazon.redshift.jdbc42.Driver
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
  at java.base/java.lang.Class.forName0(Native Method)
  at java.base/java.lang.Class.forName(Class.java:377)
  at groovy.sql.Sql.loadDriver(Sql.java:733)
  at groovy.sql.Sql.newInstance(Sql.java:436)
  at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
  at Script1.run(Script1.groovy:5)
  at com.wisecoders.dbs.data.task.FxGroovyTask.a(FxGroovyTask.java:58)
  at com.wisecoders.dbs.data.task.FxGroovyTask.call(FxGroovyTask.java:25)

2. Please include the DbSchema version, operating system and used database

DbSchema 8.4.2 build 210506
Redshift

3. The steps to reproduce this issue

import java.sql.*; 
import groovy.sql.Sql 

   // Creating a connection to the database
      def sql = Sql.newInstance('jdbc:redshift://hostname.com:5439/dbname', 
         'username', 'password', 'com.amazon.redshift.jdbc42.Driver')
			
      // Executing the query SELECT VERSION which gets the version of the database
      // Also using the eachROW method to fetch the result from the database
   
      sql.eachRow('select * from ngdev_models.finance_module'){ row ->
         println row[0]
      }
		
      sql.close()

**Comment by wise-coders** [comment]
You have to create the connection as in the Help  /Automation Scripts. Only like these, the drivers are loaded. The way you create a connection is the Groovy standard, where the drivers should be in the class path. But since we load them dynamically, this won't work. Please have a look on this sample:

Best regards,
 Dragos Pruteanu

PS. Any feedback about DbSchema or database-specific issues is welcome.

**Comment by sterlingalston** [comment]
This is resolved.

https://docs.aws.amazon.com/redshift/latest/mgmt/connecting-in-code.html

package connection; //added this line

import java.sql.*; 
import groovy.sql.Sql 

def env = System.getenv()

   // Creating a connection to the database
def sql = Sql.newInstance('jdbc:redshift://hostname.com:5439/dbname',
'username', 'password', 'com.amazon.redshift.jdbc42.Driver')
