### ISSUE TITLE
Log errors for pg_sequences not existing in postgresql 9.x

### ISSUE THREAD

**Issue by briffle** [wise-coders/dbschema#6]
I am using DbSchema 8.2.7 on Ubuntu 19.10.  My Postgresql version is 9.6, running on a Debian 9 server.

I keep seeing the below error in the logs. If I am reading the documentation correctly, this was added in postgresql 10, but 9.6 is still actively supported: https://www.postgresql.org/docs/10/view-pg-sequences.html

*** My Logs****
Start DbSchema.
==== 2020-02-12 11:54:50 DbSchema #200205 Java AdoptOpenJDK13 ===
Screen Size: [2827.0,1599.0] outputScaleY=1.0 scaleDown=false
Open Project 'PostgreSQL' PostgreSQL 569 Tables, 13 Layouts, 0 Browse Editors, 0 Sql Editors
 > synchronizeRefreshSelected
Synchronize schemas in REFRESH mode selection [<redacted>]
Connect: PostgreSQL
Connected.
Dialog Selection Dialog
org.postgresql.util.PSQLException: ERROR: relation "pg_catalog.pg_sequences" does not exist
  Position: 39
  at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
  at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
  at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
  at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
  at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
  at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
  at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
  at com.wisecoders.dbs.rdbms.connect.model.envoy.DirectQuery.a(DirectQuery.java:94)
  at com.wisecoders.dbs.rdbms.connect.model.envoy.Envoy.a(Envoy.java:102)
  at com.wisecoders.dbs.rdbms.reverseEngineer.model.ImporterUtils.d(ImporterUtils.java:263)
  at com.wisecoders.dbs.rdbms.Rdbms.listSequences(Rdbms.java:448)
  at com.wisecoders.dbs.rdbms.reverseEngineer.model.StructureImporter.a(StructureImporter.java:65)
  at com.wisecoders.dbs.rdbms.reverseEngineer.model.StructureImporter.<init>(StructureImporter.java:21)
  at com.wisecoders.dbs.rdbms.reverseEngineer.fx.FxImportStructureTask$1.<init>(FxImportStructureTask.java:40)
  at com.wisecoders.dbs.rdbms.reverseEngineer.fx.FxImportStructureTask.a(FxImportStructureTask.java:40)
  at com.wisecoders.dbs.rdbms.reverseEngineer.fx.FxImportStructureTask.call(FxImportStructureTask.java:14)
  ...

**Comment by wise-coders** [comment]
Could you please delete the folder .DbSchema from C:\Users\<yourUser>?
This will delete all local caches. Connecting to PostgreSQL you will need to switch forth and back to a different database, so the driver is downloaded again from website.

Then please try again. Please also check the Project /Settings / PostgreSQL Reverse Engineer / Sequences, the query should be 
`SELECT sequence_name, start_value FROM information_schema.sequences WHERE sequence_schema='${schema}'`

Please let me know if you still get errors even using this query - we will start testing intensive with PostgreSQL 9.6.

![image](https://user-images.githubusercontent.com/60284259/74812582-0b1a6b00-52f4-11ea-83f1-17f9b19025b7.png)

**Comment by briffle** [comment]
Thank you, this appears to have cleared up that log issue!
